site_title: OKA UKDW 2020
site_subtitle: Melibatkan Diri Dalam Pemulihan Keutuhan Ciptaan
site_copyright: Universitas Kristen Duta Wacana
site_date: 8 - 11 September 2020
theme: Travelify
rewrite_url: true